### ISSUE TITLE
Install and configure moonlight-embedded

### ISSUE THREAD

**Issue by link-webcreations** [nVentiveUX/rpi-ansible#2]
Install moonlight-embedded using 👍 https://github.com/link-webcreations/moonlight-config
This works perfectly when installing manually.
So the aim is to

* Install it using ansible
* Add the ability to launch the stream without keyboard connected on the PI (Send a command from the PC thought SSH on the session connected thought HDMI and showed by the TV)

**Comment by bigbrozer** [comment]
We should put that in `roles/moonlight`.
